# Nome: Henrique Augusto Gomes Togo
# Matrícula: 231111280

## Questão 2

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
arr_pca = np.loadtxt("data_pca_question.csv", delimiter=",", dtype=float)
mean_vec_pca = np.mean(arr_pca, axis=0)
std_vec_pca = np.sqrt(np.var(arr_pca, axis=0))
for i in range(len(mean_vec_pca)):
    print(f'Média x{i + 1} = {mean_vec_pca[i]:.2f}')
    print(f'Desvio Padrão x{i + 1} = {std_vec_pca[i]:.2f}')
    print(40*'=')

Média x1 = 2.52
Desvio Padrão x1 = 1.41
Média x2 = -2.81
Desvio Padrão x2 = 5.38
Média x3 = 0.30
Desvio Padrão x3 = 9.36


In [3]:
pca_normal = (arr_pca - mean_vec_pca)/std_vec_pca

mean_pca_normal = np.mean(pca_normal, axis=0)
std_pca_normal = np.sqrt(np.var(pca_normal, axis=0))
for i in range(len(mean_pca_normal)):
    print(f'Média z{i + 1} = {mean_pca_normal[i]:.2f}')
    print(f'Desvio Padrão z{i + 1} = {std_pca_normal[i]:.2f}')
    print(40*'=')

Média z1 = -0.00
Desvio Padrão z1 = 1.00
Média z2 = 0.00
Desvio Padrão z2 = 1.00
Média z3 = -0.00
Desvio Padrão z3 = 1.00


In [4]:
cov_vec_pca = np.cov(np.transpose(pca_normal))
print(f'S = {cov_vec_pca}')

S = [[ 1.001001   -0.53439232 -0.60672834]
 [-0.53439232  1.001001    0.94108144]
 [-0.60672834  0.94108144  1.001001  ]]


In [5]:
eigenvalues_pca, eigenvectors_pca = np.linalg.eig(cov_vec_pca) 
eigen_pca = [] # Tuples (eigenvalue, eigenvector)
for i in range(len(eigenvalues_pca)):
    eigen_pca.append((eigenvalues_pca[i], eigenvectors_pca[:,i]))
eigen_pca = sorted(eigen_pca, key=lambda element:(element[0]), reverse=True)

for i in range(len(eigenvalues_pca)):
    print(f'Autovalor {i + 1}: {eigen_pca[i][0]}\nAutovetor {i + 1}: {eigen_pca[i][1]}')

Autovalor 1: 2.4058885474588987
Autovetor 1: [ 0.49831409 -0.60532847 -0.62069357]
Autovalor 2: 0.5415530005252888
Autovetor 2: [-0.86283557 -0.41630393 -0.28671556]
Autovalor 3: 0.055561455018817284
Autovetor 3: [ 0.08484009 -0.6784309   0.72974905]


In [10]:
eigenvalues_total = np.sum(eigenvalues_pca)
for i in range(len(eigen_pca)):
    print(f'Porcentagem do Autovalor {i + 1}: {(100 * eigen_pca[i][0] / eigenvalues_total):.2f}%')

Porcentagem do Autovalor 1: 80.12
Porcentagem do Autovalor 2: 18.03
Porcentagem do Autovalor 3: 1.85


In [7]:
k_order_pca = 2
w_list = []
for i in range(k_order_pca):
    w_list.append(eigen_pca[i][1])

w = np.transpose(np.array(w_list))
print(w)

[[ 0.49831409 -0.86283557]
 [-0.60532847 -0.41630393]
 [-0.62069357 -0.28671556]]


In [8]:
z = np.zeros((k_order_pca, len(pca_normal)))
for i in range(len(pca_normal)):
    z[:, i] = np.transpose(w) @ (pca_normal[i] - mean_vec_pca)
z = np.transpose(z)

np.var(z, axis=0)

array([2.40348266, 0.54101145])